### PR TITLE
Scripture Takes Flowpane

### PR DESCRIPTION
**Pull request by KJoslyn**
`TakesFlowPane` now fills out the last row of take cards with blank take cards. When the alternate takes list is changed, or when the window is resized, blank cards are added or removed appropriately.

To test, either run `main` in Main.kt and drill down to a scripture takes page, or checkout [takes-flowpane-testapp](https://github.com/WycliffeAssociates/otter-jvm/tree/takes-flowpane-testapp) and run `main` in RecordScriptureTestApp, which brings you directly to the scripture takes page.

---
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/478)

### CODE REVIEW

**Review by aunger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/478)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @KJoslyn)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/takemanagement/view/TakesFlowPane.kt, line 32 at r3](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/478#-LmlNWjaAbj4htlQCg4s:-LmlNWjaAbj4htlQCg4t:bw3j4bu) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/4b5fff250855e3636e07a4b1011884658e0fdcb6/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/takemanagement/view/TakesFlowPane.kt#L32)):*
> ```Kotlin
>     override fun layoutChildren() {
>         super.layoutChildren()
>         if (!isStageShownProperty.value) {
> ```

Minor: Consider reversing if/else so predicate isn't negative
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/takemanagement/view/TakesFlowPane.kt, line 93 at r3](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/478#-LmlNnMk50yv1RzEJkrc:-LmlNnMk50yv1RzEJkrd:b-1kt5jh) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/4b5fff250855e3636e07a4b1011884658e0fdcb6/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/takemanagement/view/TakesFlowPane.kt#L93)):*
> ```Kotlin
>         // can easily overflow to a second row. In this case, we should underestimate the amount of space we have.
>         if (getNonBlankChildren().size <= roundedMax &&
>             nonRoundedMax - roundedMax < 0.02
> ```

Minor: 
combine lines
also consider pulling return out of if/else

**Review by aunger — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 4 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/478)* status: all files reviewed, 2 unresolved discussions (waiting on @KJoslyn)

**Review by aunger — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/478)* status: all files reviewed, 2 unresolved discussions (waiting on @KJoslyn)

**Review by KJoslyn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/478)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @aunger)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/takemanagement/view/TakesFlowPane.kt, line 32 at r3](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/478#-LmlNWjaAbj4htlQCg4s:-LmtrEV6D0aWW3-XX2ZB:b-7iek9c) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/4b5fff250855e3636e07a4b1011884658e0fdcb6/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/takemanagement/view/TakesFlowPane.kt#L32)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Minor: Consider reversing if/else so predicate isn't negative
</blockquote></details>

Yep, that's better. Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/takemanagement/view/TakesFlowPane.kt, line 93 at r3](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/478#-LmlNnMk50yv1RzEJkrc:-LmtrLJ_5VDOlYtHOQiZ:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/4b5fff250855e3636e07a4b1011884658e0fdcb6/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/takemanagement/view/TakesFlowPane.kt#L93)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Minor: 
combine lines
also consider pulling return out of if/else
</blockquote></details>

Done.

**Review by aunger — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/478)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request closed without merging**
