### PR TITLE
Ns placeholder bug

### PR DESCRIPTION
**Pull request by natibekele**
references https://bttrecorder.atlassian.net/browse/OT-12 and 
https://bttrecorder.atlassian.net/browse/OT-15

problem arose from conflicting css classes

---
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/504)

### CODE REVIEW

**Review by KJoslyn — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/504)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aunger and @sarabiaj)

**Review by aunger — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/504)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aunger and @sarabiaj)

**Review by aunger — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/504)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarabiaj)

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/504#-:-Lo_e2jb5RWokGhD8xSw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarabiaj)

**Pull request merged**
