### PR TITLE
Remove ResourceInfo and convert to ResourceMetadata

### PR DESCRIPTION
**Pull request by KJoslyn**
Requires common [#129](https://github.com/WycliffeAssociates/otter-common/pull/129)

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/495)

### CODE REVIEW

**Review by aunger — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/495)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @KJoslyn)

*[a discussion](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/495#-LnvBtUPEudpC90RSOIa:-LnvBtUQ5-XEMg0HlU4b:bplffm0) (no related file):*
ResourceInfo was intentionally different than ResourceMetadata: just what was needed in the workbook model, simpler, without a database row id. This seems like a step backwards.

---

**Review by aunger — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/495#-:-Lo11A_4DgOpxFhhhAK3:bnfp4nl)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @KJoslyn)

**Review by jsarabia — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/495#-:-LoM4iZs3ZxP3pp4fZlC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @aunger)

*[a discussion](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/495#-LnvBtUPEudpC90RSOIa:-LoM4cob9MTx6duycnBd:b9k47qx) (no related file):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

ResourceInfo was intentionally different than ResourceMetadata: just what was needed in the workbook model, simpler, without a database row id. This seems like a step backwards.
</blockquote></details>

Compromised by setting vars to vals in ResourceMetadata

---

**Review by jsarabia — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/495)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
