### PR TITLE
Remove resource tabs when the workbook changes

### PR DESCRIPTION
**Pull request by KJoslyn**
Fixes bug [OT-20](https://bttrecorder.atlassian.net/jira/software/projects/OT/boards/1/backlog?selectedIssue=OT-20)

---
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/506)

### CODE REVIEW

**Comment by jsarabia** [comment]
I don't feel like this belongs here? Why not do it when a different workbook is selected?

**Review by KJoslyn — COMMENTED** [review]
That's what I'm doing? If I put the logic in another file, it has to have some method to call on the tabgroup

> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/506#-:-Lo_ylrI7MnlRLZFjbAV:bist02j)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @sarabiaj)

**Review by jsarabia — COMMENTED** [review]
What about when the user selects a book though?

> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/506#-:-Loa1S7L6gWSLyT3A9tL:b9hgi67)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @sarabiaj)

**Review by aunger — APPROVED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/506)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarabiaj)

**Review by aunger — APPROVED** [review]

**Pull request merged**
