### PR TITLE
Move the build to travis

### PR DESCRIPTION
**Pull request by danparisd**
This moves the build completely into Travis. It's currently broken in Jenkins, so moving it to travis solves 2 problems. One, it gets the build fixed. Two, it will prevent us from breaking the build in the future without knowing we broke it. This change will also allow us to more easily share nightly builds as they are moved into an S3 bucket instead of a local share.

This does not include @aunger latest changes (currently a PR) to build.gradle. We'll need to merge these changes carefully, but it shouldn't be too bad.

---
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486)

### CODE REVIEW

**Review by aunger — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @aunger, @danparisd, and @sarabiaj)

___
*[.travis.yml, line 15 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJMmHVC6Jpx9GHClFV:-LnJMmHWAkN0rWDjfMtU:blf78nl) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L15)):*
> ```YAML
>   - "$HOME/.gradle/wrapper"
> before_install:
> - wget --no-verbose https://download-gcdn.ej-technologies.com/install4j/install4j_unix_7_0_12.tar.gz
> ```

wget here and curl below. Can they be standardized?
___
*[.travis.yml, line 15 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJMwAm7TB2mqe36EE2:-LnJMwAm7TB2mqe36EE3:b-z41swm) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L15)):*
> ```YAML
>   - "$HOME/.gradle/wrapper"
> before_install:
> - wget --no-verbose https://download-gcdn.ej-technologies.com/install4j/install4j_unix_7_0_12.tar.gz
> ```

CDN URL here and two different hosts below (download.ej-technologies, s3). Can they be standardized?  Fewer URLs means fewer chances a build breaks on external failures.
___
*[.travis.yml, line 20 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJKomT4gDINszD03p7:-LnJKomU1HgpAvwMco_l:b9w6bwr) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L20)):*
> ```YAML
> - curl -C - -LR#O "https://download.ej-technologies.com/bundles/packed2/windows-amd64-1.8.0_192.tar.gz"
> - curl -C - -LR#O "https://download.ej-technologies.com/bundles/packed2/macosx-amd64-1.8.0_192.tar.gz"
> - curl -C - -LR#O "http://otter-build-nightly.s3-website-us-east-1.amazonaws.com/linux-amd64-1.8.0_192.tar.gz"
> ```

Are these three JVM downloads? It's not clear. Please add comments.
___
*[.travis.yml, line 20 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJOq149inyCZ4ekCSS:-LnJOq149inyCZ4ekCST:bkqah9i) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L20)):*
> ```YAML
> - curl -C - -LR#O "https://download.ej-technologies.com/bundles/packed2/windows-amd64-1.8.0_192.tar.gz"
> - curl -C - -LR#O "https://download.ej-technologies.com/bundles/packed2/macosx-amd64-1.8.0_192.tar.gz"
> - curl -C - -LR#O "http://otter-build-nightly.s3-website-us-east-1.amazonaws.com/linux-amd64-1.8.0_192.tar.gz"
> ```

Some of these curl options are confusing. (Are you continuing a previous download? Do you really want to force HTTP 1.0 protocol?)  Please add comments for the important options and remove the unimportant ones.
___
*[.travis.yml, line 22 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJSAitDCtt1CRHdlTk:-LnJSAitDCtt1CRHdlTl:bpd60ye) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L22)):*
> ```YAML
> - curl -C - -LR#O "http://otter-build-nightly.s3-website-us-east-1.amazonaws.com/linux-amd64-1.8.0_192.tar.gz"
> install:
> - git clone --branch=jbs-otter-css https://github.com/WycliffeAssociates/chromeabletabpane.git
> ```

This looks like @sarabiaj 's four-month-old feature branch.  Can we get it merged into dev or master?
___
*[.travis.yml, line 57 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJPUSm4pCU1tQ_NaiI:-LnJPUSm4pCU1tQ_NaiJ:b-ptl4q2) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L57)):*
> ```YAML
>   file_glob: true
>   on:
>     tags: true
> ```

Looks like this configures a release for tags. How are the nightly releases configured?

**Comment by aunger** [comment]
___
*[.travis.yml, line 20 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJOq149inyCZ4ekCSS:-LnJUK3uDf74hMsUWWsR:bn92cc1) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L20)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Some of these curl options are confusing. (Are you continuing a previous download? Do you really want to force HTTP 1.0 protocol?)  Please add comments for the important options and remove the unimportant ones.
</blockquote></details>

Oops, I misread -O as -0. Still, you may want `--retry` instead of `-C -`.

**Review by danparisd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @aunger, @danparisd, and @sarabiaj)

___
*[.travis.yml, line 15 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJMwAm7TB2mqe36EE2:-LnJUIBO7fa1MaRfvuiw:b-brr0kr) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L15)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

CDN URL here and two different hosts below (download.ej-technologies, s3). Can they be standardized?  Fewer URLs means fewer chances a build breaks on external failures.
</blockquote></details>

The URLs are what ej-technologies provided. We can't avoid downloading the needed dependencies. The links I've used appear to be intended as perma-links. 
___
*[.travis.yml, line 15 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJMmHVC6Jpx9GHClFV:-LnJa-d83UTmqXGqhI1s:b-idx5sl) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L15)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

wget here and curl below. Can they be standardized?
</blockquote></details>

Giving this a try. wget is the better tool for downloads, but downloading the JRE from oracle required a header and curl magic, so most of that was remnants of downloading JRE's from Oracle, which we can't do any longer.
___
*[.travis.yml, line 20 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJKomT4gDINszD03p7:-LnJafxTC9g8iXuQu7A5:b51kggp) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L20)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Are these three JVM downloads? It's not clear. Please add comments.
</blockquote></details>

added comments
___
*[.travis.yml, line 22 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJSAitDCtt1CRHdlTk:-LnJajnu1sQkohXdxk9g:bsbgpno) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L22)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

This looks like @sarabiaj 's four-month-old feature branch.  Can we get it merged into dev or master?
</blockquote></details>

Not a change I made. This is how it exists in Dev.
___
*[.travis.yml, line 57 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJPUSm4pCU1tQ_NaiI:-LnJarlPA0xY5DRRBGdo:banu8jz) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L57)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Looks like this configures a release for tags. How are the nightly releases configured?
</blockquote></details>

Nightlies are uploaded to S3 for any successful Travis build coming from a branch.

**Review by danparisd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @aunger and @sarabiaj)

___
*[.travis.yml, line 20 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJOq149inyCZ4ekCSS:-LnJc7mx9d7O_WN2KI5G:bsetnjg) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L20)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Oops, I misread -O as -0. Still, you may want `--retry` instead of `-C -`.
</blockquote></details>

wget appears to work fine.

**Review by danparisd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @aunger and @sarabiaj)

___
*[.travis.yml, line 57 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJPUSm4pCU1tQ_NaiI:-LnJcLM_6ZurWvTEVTb7:b-v8rq4t) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L57)):*
<details><summary><i>Previously, danparisd wrote…</i></summary><blockquote>

Nightlies are uploaded to S3 for any successful Travis build coming from a branch.
</blockquote></details>

@sarabiaj we may want to only push to s3 on dev and master branches, which I think we can do, but I'll have to figure out how to change it, It's not documented, but it appears it can be done.

**Review by aunger — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486)* status: all files reviewed, 1 unresolved discussion (waiting on @danparisd and @sarabiaj)

___
*[.travis.yml, line 15 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJMwAm7TB2mqe36EE2:-LnJjFaPB19i8gGvp2Ul:b-53any5) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L15)):*
<details><summary><i>Previously, danparisd wrote…</i></summary><blockquote>

The URLs are what ej-technologies provided. We can't avoid downloading the needed dependencies. The links I've used appear to be intended as perma-links. 
</blockquote></details>

OK. Just for discussion:

Although we can't eliminate external dependencies, I'm looking for ways to reduce them. As is, our build & PR system will be unavailable when Travis, either of the EJ servers, Github, _or_ S3 is down.

I see you're keeping the Linux JVM on S3. I'm just wondering if the dev process will be more robust if you do more of this.
___
*[.travis.yml, line 22 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJSAitDCtt1CRHdlTk:-LnJj5dO-M2u9Cz6z3UH:bjjhrus) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L22)):*
<details><summary><i>Previously, danparisd wrote…</i></summary><blockquote>

Not a change I made. This is how it exists in Dev.
</blockquote></details>

OK.  Spawned #488

**Review by danparisd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486)* status: all files reviewed, 1 unresolved discussion (waiting on @aunger and @sarabiaj)

___
*[.travis.yml, line 15 at r4](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-LnJMwAm7TB2mqe36EE2:-LnJr-L35LD2ty437-p7:bd3vs58) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/b8216b76e178b331f7dfbf15dd8211d8a5e35b7a/.travis.yml#L15)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

OK. Just for discussion:

Although we can't eliminate external dependencies, I'm looking for ways to reduce them. As is, our build & PR system will be unavailable when Travis, either of the EJ servers, Github, _or_ S3 is down.

I see you're keeping the Linux JVM on S3. I'm just wondering if the dev process will be more robust if you do more of this.
</blockquote></details>

understood. Technically speaking, install4j does not recommend doing what we are doing with the linux JVM. They provide their own JRE bundles for Windows and Mac as they recommend bundling them, but they don't recommend bundling the linux JRE so I was downloading it from oracle and using their tool to re-package it like their installer likes it. The one that's uploaded to S3 is one I bundled myself and put up there instead of hosting the JRE and re-bundling it every time we just host the re-bundled JRE.

**Review by aunger — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarabiaj)

**Comment by jsarabia** [comment]
This is still using java 8

**Review by jsarabia — CHANGES_REQUESTED** [review]
Please update from java 8 to java 11.

I've also updated this file in another pr for the chromeabletabpane to use the master branch (I merged the feature branch), so you might want to pull that change in

**Review by aunger — APPROVED** [review]

**Comment by danparisd** [comment]
@sarabiaj I'm still working on this. I need to talk to you about how we handle the JRE bundles.

**Review by aunger — CHANGES_REQUESTED** [review]
.

> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486#-:-LoRtPQr4JWFR-dxvhAU:b3kqx)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @aunger)

**Review by aunger — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/486)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by danparisd** [comment]
I'll reopen this when I complete the move to corretto JRE

**Pull request closed without merging**
