### PR TITLE
Ns progress stepper

### PR DESCRIPTION
**Pull request by natibekele**
resolves 
https://bttrecorder.atlassian.net/browse/OT-4
https://bttrecorder.atlassian.net/browse/OT-7
https://bttrecorder.atlassian.net/browse/OT-6

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502)

### CODE REVIEW

**Review by aunger — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502)* status: all files reviewed, 14 unresolved discussions (waiting on @natibekele and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 17 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRg-IQ889bqjubzJxD:-LoRg-IQ889bqjubzJxE:b-7estnk) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L17)):*
> ```Kotlin
>     val wizardWorkspace = Workspace()
> 
>     data class stepItem(val stepText: String, val stepGraphic: Node, val completedText: SimpleStringProperty)
> ```

Please split the vals onto separate lines
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 21 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRg9hnBtTztT5YXzhL:-LoRg9hnBtTztT5YXzhM:b-y3mgf1) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L21)):*
> ```Kotlin
>     val stepList: List<stepItem> = listOf(
>         stepItem(
>             stepText = "Select a Language",
> ```

Internationalization i18n
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 26 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRgCc45FezfBtIZc8C:-LoRgCc45FezfBtIZc8D:bb7gyar) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L26)):*
> ```Kotlin
>         ),
>         stepItem(
>             stepText = "Select a Resource",
> ```

i18n
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 31 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRgDn82WZUZvnwuhUT:-LoRgDn82WZUZvnwuhUU:bb7gyar) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L31)):*
> ```Kotlin
>         ),
>         stepItem(
>             stepText = "Select a Book",
> ```

i18n
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 46 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRhgeV0UAeVjTLV3ia:-LoRhgeV0UAeVjTLV3ib:b-e7ykjr) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L46)):*
> ```Kotlin
>                 paddingAll = 24.0
>                 add(progressstepper {
>                     stepList.forEachIndexed { x, stepItem ->
> ```

Nit: Use `i` or `index` for the index
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 53 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRgZnxAexZHvqn9oLs:-LoRgZnxAexZHvqn9oLt:bu6izg0) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L53)):*
> ```Kotlin
>                                 completedTextProperty.bind(stepItem.completedText)
>                             })
>                         } else add(step(separator = false) {
> ```

I suggest you combine the `if` & `else` bodies ([D.R.Y.](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)) and instead use `step(separator = x < stepList.size - 1)`
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizardStyles.kt, line 29 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRjGHUEMa-05JNo0H0:-LoRjGHV2AzIjroM_-4w:bn9ok30) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizardStyles.kt#L29)):*
> ```Kotlin
>         val languageSearchContainer by cssclass()
>         val searchableTargetList by cssclass()
>         val searchableSourceList by cssclass()
> ```

Should the old `searchableList` CSS class be removed, or is it still used elsewhere?
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizardStyles.kt, line 171 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRk-9b7VQmNy67tVUh:-LoRk-9b7VQmNy67tVUi:b-1saj28) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizardStyles.kt#L171)):*
> ```Kotlin
>             }
>         }
>         searchableSourceList {
> ```

Nit: Blank line between styles
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizardStyles.kt, line 171 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRkLg0CD8euNDglJr5:-LoRkLg0CD8euNDglJr6:b6awg7a) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizardStyles.kt#L171)):*
> ```Kotlin
>             }
>         }
>         searchableSourceList {
> ```

`searchableSourceList` and `searchableTargetList` appear extremely similar.  Does jfx have a mechanism for defining the similarities in, say, a base class like `sourceList`, and the specifics in children `searchableSourceList` and `searchableTargetList`?
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/viewmodel/ProjectWizardViewModel.kt, line 68 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRlAnT-EuP9rNtlgiQ:-LoRlAnT-EuP9rNtlgiR:b85g4s0) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/viewmodel/ProjectWizardViewModel.kt#L68)):*
If I see the same function called with different parameters in close proximity, I usually look for another way, e.g.:
> ```
>         targetLanguageProperty.onChange {
>             languageCompletedText.set(it?.anglicizedName)
>         }
> ```
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/viewmodel/ProjectWizardViewModel.kt, line 108 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRm7daAkhSkUufvaPz:-LoRm7daAkhSkUufvaQ-:b-va6ig1) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/viewmodel/ProjectWizardViewModel.kt#L108)):*
> ```Kotlin
>             createProject(selectedCollection)
>         } else {
>             if (selectedCollection.labelKey == "bundle") resourceCompletedText.set(selectedCollection.titleKey)
> ```

Add braces to this `if` body, so your intention is clear. I know you probably only want this single line to run conditionally, but with the funny nesting, it's a little hard to read.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/ProgressStepper.kt, line 33 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRoHpF4gz3ysdWIkH1:-LoRoHpG6nXk1nZUjoQ7:b-ow3u9w) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/ProgressStepper.kt#L33)):*
> ```Kotlin
> }
> 
> fun progressstepper(init: ProgressStepper.() -> Unit = {}): ProgressStepper {
> ```

Should this be camelCase?
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/workpagelist/WorkbookList.kt, line 23 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRquq7DMpoAZK2TkCS:-LoRquq7DMpoAZK2TkCT:bsu7l8f) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/workpagelist/WorkbookList.kt#L23)):*
> ```Kotlin
> class BookCardMapper {
>     companion object {
>         fun mapTopChapters(bookElement: BookElement) {
> ```

typo? top/to
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/workpagelist/WorkbookList.kt, line 27 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRr08O0JxrGmxeFogl:-LoRr08O0JxrGmxeFogm:b-djptov) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/workpagelist/WorkbookList.kt#L27)):*
> ```Kotlin
> 
>         fun mapToChunks(bookElement: BookElement) {
>         }
> ```

Should these functions have bodies?

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502)* status: all files reviewed, 16 unresolved discussions (waiting on @aunger and @natibekele)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 59 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoVSk5H0Nm-ggjtHomt:-LoVSk5H0Nm-ggjtHomu:b-mwjk8k) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L59)):*
> ```Kotlin
>                         })
>                     }
>                 })
> ```

lots of }) that should be expanded out
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/ProgressStepper.kt, line 33 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRoHpF4gz3ysdWIkH1:-LoVRwr-1lPlSPGY7uwZ:b-mnut4y) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/ProgressStepper.kt#L33)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Should this be camelCase?
</blockquote></details>

He's trying to follow the precedence set by tornadoFx's other builders such as "stackpane" 
I agree this looks rough.
How about just renaming ProgressStepper to Stepper?
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/Step.kt, line 63 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoVSbLq5yPeaUVDi-WM:-LoVSbLq5yPeaUVDi-WN:b-740793) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/Step.kt#L63)):*
> ```Kotlin
>                 toggleClass(ProgressStepperStyles.completedBar, completedTextProperty.booleanBinding {
>                     it != null
>                 })
> ```

put the argument on its own line

**Review by natibekele — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502)* status: 1 of 9 files reviewed, 12 unresolved discussions (waiting on @aunger and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 17 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRg-IQ889bqjubzJxD:-LoVj4YU7bzGwjMR8r5T:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L17)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Please split the vals onto separate lines
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 21 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRg9hnBtTztT5YXzhL:-LoVj48w-xae3ypojt0d:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L21)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Internationalization i18n
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 26 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRgCc45FezfBtIZc8C:-LoVj3lH6IEIjPqr-fF_:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L26)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

i18n
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 31 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRgDn82WZUZvnwuhUT:-LoVj3_mCEooBe6mzLni:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L31)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

i18n
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 53 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRgZnxAexZHvqn9oLs:-LoVj2OxBpFggyPb0yFd:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L53)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

I suggest you combine the `if` & `else` bodies ([D.R.Y.](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)) and instead use `step(separator = x < stepList.size - 1)`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 59 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoVSk5H0Nm-ggjtHomt:-LoVj24e2slZW7-NHLk0:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L59)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

lots of }) that should be expanded out
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizardStyles.kt, line 171 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRkLg0CD8euNDglJr5:-LoVj-zB5QC76nskJWWL:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizardStyles.kt#L171)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

`searchableSourceList` and `searchableTargetList` appear extremely similar.  Does jfx have a mechanism for defining the similarities in, say, a base class like `sourceList`, and the specifics in children `searchableSourceList` and `searchableTargetList`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/viewmodel/ProjectWizardViewModel.kt, line 68 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRlAnT-EuP9rNtlgiQ:-LoV_MwYAmxsSH_k5azs:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/viewmodel/ProjectWizardViewModel.kt#L68)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

If I see the same function called with different parameters in close proximity, I usually look for another way, e.g.:
> ```
>         targetLanguageProperty.onChange {
>             languageCompletedText.set(it?.anglicizedName)
>         }
> ```

</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/viewmodel/ProjectWizardViewModel.kt, line 108 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRm7daAkhSkUufvaPz:-LoV_ME7E5DhYL3IqqKI:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/viewmodel/ProjectWizardViewModel.kt#L108)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Add braces to this `if` body, so your intention is clear. I know you probably only want this single line to run conditionally, but with the funny nesting, it's a little hard to read.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/Step.kt, line 63 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoVSbLq5yPeaUVDi-WM:-LoV_Iyl3mccACyRhs3_:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/Step.kt#L63)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

put the argument on its own line
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/workpagelist/WorkbookList.kt, line 23 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRquq7DMpoAZK2TkCS:-LoV_He5BmdrDqHDiIne:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/workpagelist/WorkbookList.kt#L23)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

typo? top/to
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/workpagelist/WorkbookList.kt, line 27 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRr08O0JxrGmxeFogl:-LoV_I0N73NcanIiX8ZQ:b-896fix) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/workpagelist/WorkbookList.kt#L27)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Should these functions have bodies?
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502)* status: 1 of 9 files reviewed, 12 unresolved discussions (waiting on @aunger, @natibekele, and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 59 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoVSk5H0Nm-ggjtHomt:-LoVn3_a9znD07Pa2kWB:bkclf6p) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L59)):*
<details><summary><i>Previously, natibekele wrote…</i></summary><blockquote>

Done.
</blockquote></details>

formatting still isn't correct
lines: 
49, 51 of ProjectWizard.kt
61 of Step.kt
Also, please run the autoformatter on all files

**Review by aunger — APPROVED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502)* status: all files reviewed, 2 unresolved discussions (waiting on @natibekele and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/ProgressStepper.kt, line 33 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-LoRoHpF4gz3ysdWIkH1:-LoW7RXa3M8Ps4CCYZC9:bb6ywmx) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/59601eb563099ded159bd1342cce8e0411b1a366/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/ProgressStepper.kt#L33)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

He's trying to follow the precedence set by tornadoFx's other builders such as "stackpane" 
I agree this looks rough.
How about just renaming ProgressStepper to Stepper?
</blockquote></details>

LGTM

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/502#-:-LoWIBxOE41I79Np-ll3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sarabiaj)

**Pull request merged**
