### PR TITLE
Only create content derivative entries for text contents

### PR DESCRIPTION
**Pull request by KJoslyn**
Entries in the content derivative table are now only be created for contents that are of type `ContentType.TEXT`. Furthermore, when fetching sources, we now ensure that the source and derived ContentTypes are the same. (Before, when we were creating content derivative entries for Resource types such as TITLE and BODY, these types were getting intermingled with the TEXT and META types.)

---
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498)

### CODE REVIEW

**Review by KJoslyn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/persistence/database/daos/ContentDao.kt, line 103 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498#-LoMJk5J4r1UV0deUph5:-LoMJk5J4r1UV0deUph6:bmrxhqj) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/ea5d0eeebadf73a68bcbfdd61b79f9d2e502bc06/src/main/kotlin/org/wycliffeassociates/otter/jvm/persistence/database/daos/ContentDao.kt#L103)):*
> ```Kotlin
>                 .from(CONTENT_DERIVATIVE)
>                 .where(CONTENT_DERIVATIVE.CONTENT_FK.eq(entity.id))
>                 .fetch {
> ```

If we didn't want to use try-catch, I could have done

```
            .fetchAnyArray()
            ?.let { results ->
                (results as? Array<Record1<Int>>)?.map {
                    it.getValue(CONTENT_DERIVATIVE.SOURCE_FK)
                }
            }
            ?: return listOf()
```

But this leads to an unchecked cast warning which I'd have to suppress. I didn't really see a cleaner way to do the fetch where I expect that the number of entries fetched might be 0.

**Review by KJoslyn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/persistence/repositories/CollectionRepository.kt, line 412 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498#-LoMK2BM3yp6Tu97uogo:-LoMK2BM3yp6Tu97uogp:b8ioqwj) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/ea5d0eeebadf73a68bcbfdd61b79f9d2e502bc06/src/main/kotlin/org/wycliffeassociates/otter/jvm/persistence/repositories/CollectionRepository.kt#L412)):*
> ```Kotlin
>                                     // Only create content derivative entries for text contents
>                                     CONTENT_ENTITY.TYPE_FK.eq(
>                                         contentTypeDao.fetchId(ContentType.TEXT)
> ```

I assume that there is no reason to create content derivative entries for META contents since chunking will not affect the chapters.

**Review by aunger — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498)* status: all files reviewed, 4 unresolved discussions (waiting on @KJoslyn and @sarabiaj)

*[a discussion](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498#-LoNyBBtEhzAc4ONWDAa:-LoNyBBtEhzAc4ONWDAb:bnqqp5z) (no related file):*
Do you think it's worth adding integration test cases to verify content derivative DB row counts?

---
*[a discussion](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498#-LoOVnI_7rZbJeC-UPXx:-LoOVnIa-5ONO7aHo6g6:bp0iaov) (no related file):*
Reviewing the linkContent() function was painful, and it's my own ugly code.  I refactored it in PR https://github.com/WycliffeAssociates/otter-jvm/pull/501 in case you want to add it into your branch.  If not, I'll try to get it merged in after MVP.

---
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/persistence/database/daos/ContentDao.kt, line 103 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498#-LoMJk5J4r1UV0deUph5:-LoO1-NTANpPtflQbXRA:b-6wjoca) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/ea5d0eeebadf73a68bcbfdd61b79f9d2e502bc06/src/main/kotlin/org/wycliffeassociates/otter/jvm/persistence/database/daos/ContentDao.kt#L103)):*
<details><summary><i>Previously, KJoslyn wrote…</i></summary><blockquote>

If we didn't want to use try-catch, I could have done

```
            .fetchAnyArray()
            ?.let { results ->
                (results as? Array<Record1<Int>>)?.map {
                    it.getValue(CONTENT_DERIVATIVE.SOURCE_FK)
                }
            }
            ?: return listOf()
```

But this leads to an unchecked cast warning which I'd have to suppress. I didn't really see a cleaner way to do the fetch where I expect that the number of entries fetched might be 0.
</blockquote></details>

This whole thing could be more efficiently rewritten as a single DB query with a join.  If you don't want to do all that, I think you could remove the `try` and test for null:
```
.where(CONTENT_DERIVATIVE.CONTENT_FK.eq(entity.id))
.and(CONTENT_DERIVATIVE.SOURCE_FK.isNotNull) 
```
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/persistence/repositories/CollectionRepository.kt, line 412 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498#-LoMK2BM3yp6Tu97uogo:-LoOX3k81pz_tTlXuitk:bsobot3) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/ea5d0eeebadf73a68bcbfdd61b79f9d2e502bc06/src/main/kotlin/org/wycliffeassociates/otter/jvm/persistence/repositories/CollectionRepository.kt#L412)):*
<details><summary><i>Previously, KJoslyn wrote…</i></summary><blockquote>

I assume that there is no reason to create content derivative entries for META contents since chunking will not affect the chapters.
</blockquote></details>

I don't know.

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498)* status: all files reviewed, 4 unresolved discussions (waiting on @KJoslyn)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/persistence/repositories/CollectionRepository.kt, line 412 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498#-LoMK2BM3yp6Tu97uogo:-LoVhB4v77biw0agrZ9v:bmfrc51) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/ea5d0eeebadf73a68bcbfdd61b79f9d2e502bc06/src/main/kotlin/org/wycliffeassociates/otter/jvm/persistence/repositories/CollectionRepository.kt#L412)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

I don't know.
</blockquote></details>

Might be nice to have it for meta entries, then for checking you can compare a chapter recording to the source chapter

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498)* status: all files reviewed, 4 unresolved discussions (waiting on @aunger and @KJoslyn)

*[a discussion](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498#-LoNyBBtEhzAc4ONWDAa:-LoVhTMH6fAydH50JTc7:bi500ma) (no related file):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Do you think it's worth adding integration test cases to verify content derivative DB row counts?
</blockquote></details>

This seems reasonable

---

**Review by aunger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498)* status: all files reviewed, 3 unresolved discussions (waiting on @aunger and @KJoslyn)

*[a discussion](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498#-LoOVnI_7rZbJeC-UPXx:-LoW9EOq4vZEvqkEcbun:b-z2va5f) (no related file):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Reviewing the linkContent() function was painful, and it's my own ugly code.  I refactored it in PR https://github.com/WycliffeAssociates/otter-jvm/pull/501 in case you want to add it into your branch.  If not, I'll try to get it merged in after MVP.
</blockquote></details>

Defer this.

---

**Review by KJoslyn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498)* status: all files reviewed, 3 unresolved discussions (waiting on @aunger and @KJoslyn)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/persistence/database/daos/ContentDao.kt, line 103 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498#-LoMJk5J4r1UV0deUph5:-LoWrifF0ilm1qMdnGhd:bgpy8m3) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/ea5d0eeebadf73a68bcbfdd61b79f9d2e502bc06/src/main/kotlin/org/wycliffeassociates/otter/jvm/persistence/database/daos/ContentDao.kt#L103)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

This whole thing could be more efficiently rewritten as a single DB query with a join.  If you don't want to do all that, I think you could remove the `try` and test for null:
```
.where(CONTENT_DERIVATIVE.CONTENT_FK.eq(entity.id))
.and(CONTENT_DERIVATIVE.SOURCE_FK.isNotNull) 
```
</blockquote></details>

It turns out all of this is unnecessary since fetch() doesn't throw an error if it doesn't find any results after all. It simply returns an empty list, which is fine for us.

It doesn't really matter anymore, but I believe `.isNotNull` wouldn't work here anyway since the column `SOURCE_FK` isn't allowed to be null in the `CONTENT_DERIVATIVE` table

**Review by aunger — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/498)* status: all files reviewed, 3 unresolved discussions (waiting on @aunger and @KJoslyn)

**Pull request merged**
