### PR TITLE
move wizard into custom view (project creator)

### PR DESCRIPTION
**Pull request by natibekele**
moved wizard into custom view. 
current wizard still exists and is still plugged in. 
this pr just moves all of the functionality of the current wizard into a new and separate 'package'.

---
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/487)

### CODE REVIEW

**Review by aunger — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/487)* status: all files reviewed, 2 unresolved discussions (waiting on @KJoslyn, @natibekele, and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 32 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/487#-LnJXqqe1uxKO9AXGD1z:-LnJXqqf-_BSyxj02DC0:b-fvv6w8) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/f9c7c890e59a057cf73655bca13fc4fe40b7eb1b/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L32)):*
> ```Kotlin
>                 button(messages["back"]) {
>                     addClass(ProjectWizardStyles.wizardButton)
>                     enableWhen(wizardViewModel.canGoBack.and(!wizardViewModel.showOverlayProperty))
> ```

Minor:
`and` is marked as an inline operator, so you can do `enableWhen(wizardViewModel.canGoBack and !wizardViewModel.showOverlayProperty)`
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 39 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/487#-LnJY1lQ60YxWKEYazdi:-LnJY1lQ60YxWKEYazdj:bjd9cdz) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/f9c7c890e59a057cf73655bca13fc4fe40b7eb1b/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L39)):*
> ```Kotlin
>                 button(messages["next"]) {
>                     addClass(ProjectWizardStyles.wizardButton)
>                     enableWhen(wizardViewModel.canGoNext.and(wizardViewModel.languagesValid()))
> ```

Minor: inline `and` as above

**Comment by aunger** [comment]
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/viewmodel/ProjectWizardViewModel.kt, line 45 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/487#-LnJcJmy7JFOKM5OHKpQ:-LnJcJmy7JFOKM5OHKpR:bql3860) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/f9c7c890e59a057cf73655bca13fc4fe40b7eb1b/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/viewmodel/ProjectWizardViewModel.kt#L45)):*
> ```Kotlin
>     private val creationUseCase = CreateProject(collectionRepo)
> 
>     val canGoNext: BooleanProperty = SimpleBooleanProperty(false)
> ```

Unlike `canGoBack`, `canGoNext` appears never to change after init.  Is this intentional?

**Review by natibekele — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/487)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @aunger, @KJoslyn, @natibekele, and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/viewmodel/ProjectWizardViewModel.kt, line 45 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/487#-LnJcJmy7JFOKM5OHKpQ:-LnNeKwfDVE5C1I0IpjF:b-jodcfa) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/f9c7c890e59a057cf73655bca13fc4fe40b7eb1b/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/viewmodel/ProjectWizardViewModel.kt#L45)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Unlike `canGoBack`, `canGoNext` appears never to change after init.  Is this intentional?
</blockquote></details>

No this is not intentional. I missed this from the old wizard. Thank you

**Review by natibekele — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/487)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @aunger, @KJoslyn, and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 39 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/487#-LnJY1lQ60YxWKEYazdi:-LnNlKcQ3qYidwms9BD7:b-7hy70p) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/f9c7c890e59a057cf73655bca13fc4fe40b7eb1b/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L39)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Minor: inline `and` as above
</blockquote></details>

:thumbsup:

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/487)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @aunger, @KJoslyn, and @natibekele)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 39 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/487#-LnJY1lQ60YxWKEYazdi:-LnOuIe2EAbaVEgooBeF:b-av1r92) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/f9c7c890e59a057cf73655bca13fc4fe40b7eb1b/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L39)):*
<details><summary><i>Previously, natibekele wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

Has this been resolved?
___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/viewmodel/ProjectWizardViewModel.kt, line 45 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/487#-LnJcJmy7JFOKM5OHKpQ:-LnOuMkF-Zvga4XWj5IL:b-av1r92) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/f9c7c890e59a057cf73655bca13fc4fe40b7eb1b/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/viewmodel/ProjectWizardViewModel.kt#L45)):*
<details><summary><i>Previously, natibekele wrote…</i></summary><blockquote>

No this is not intentional. I missed this from the old wizard. Thank you
</blockquote></details>

Has this been resolved?

**Review by natibekele — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/487)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @aunger, @KJoslyn, and @natibekele)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt, line 39 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/487#-LnJY1lQ60YxWKEYazdi:-LnOzfnv0Z7QxlVrPTkU:bb6un1j) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/f9c7c890e59a057cf73655bca13fc4fe40b7eb1b/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/ui/projectwizard/view/ProjectWizard.kt#L39)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

Has this been resolved?
</blockquote></details>

Done

**Review by aunger — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/487)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KJoslyn)

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/487#-:-LnSYYOW-p_DLuzJ3j2k:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KJoslyn)

**Pull request merged**
