### PR TITLE
fix menu icon background bug

### PR DESCRIPTION
**Pull request by natibekele**
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/507)

### CODE REVIEW

**Review by KJoslyn — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/507)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarabiaj)

**Review by aunger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/507)* status: all files reviewed, 1 unresolved discussion (waiting on @natibekele and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/ProgressStepperStyles.kt, line 15 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/507#-LoaCfu26Z7Tjr3EDqxF:-LoaCfu38fLWdmiqGouH:b-d6vwt7) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/a54fe0f96c8eba1e88e536ceaa64b7d725cf3533/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/ProgressStepperStyles.kt#L15)):*
> ```Kotlin
> 
>         val graphicLabel by cssclass()
>         val stepGraphicContainer by cssclass()
> ```

How does this fix a bug?

**Review by natibekele — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/507)* status: all files reviewed, 1 unresolved discussion (waiting on @aunger and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/ProgressStepperStyles.kt, line 15 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/507#-LoaCfu26Z7Tjr3EDqxF:-LoaCyeC3HGT45-XxAvs:b-fa8c4s) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/a54fe0f96c8eba1e88e536ceaa64b7d725cf3533/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/ProgressStepperStyles.kt#L15)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

How does this fix a bug?
</blockquote></details>

there was a bug that was causing the icons in the menu to have red backgrounds after you opened the wizard. this was happening because the css that was being defined in the progress stepper styles was overriding a css style from the Menu Styles.

**Review by aunger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/507)* status: all files reviewed, 1 unresolved discussion (waiting on @natibekele and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/ProgressStepperStyles.kt, line 15 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/507#-LoaCfu26Z7Tjr3EDqxF:-LoaDpqqBu-qcRyGiP8O:bgr9dmp) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/a54fe0f96c8eba1e88e536ceaa64b7d725cf3533/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/ProgressStepperStyles.kt#L15)):*
<details><summary><i>Previously, natibekele wrote…</i></summary><blockquote>

there was a bug that was causing the icons in the menu to have red backgrounds after you opened the wizard. this was happening because the css that was being defined in the progress stepper styles was overriding a css style from the Menu Styles.
</blockquote></details>

Are you saying there was another style already named graphicContainer?

**Review by aunger — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/507)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/ProgressStepperStyles.kt, line 15 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-jvm/507#-LoaCfu26Z7Tjr3EDqxF:-LoaEi0C-dNV6RUD8ZW_:b-pjx1q7) ([raw file](https://github.com/wycliffeassociates/otter-jvm/blob/a54fe0f96c8eba1e88e536ceaa64b7d725cf3533/src/main/kotlin/org/wycliffeassociates/otter/jvm/app/widgets/progressstepper/ProgressStepperStyles.kt#L15)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Are you saying there was another style already named graphicContainer?
</blockquote></details>

Looks like that's the case.  Assuming so, LGTM

**Pull request merged**
